### ISSUE TITLE
Has a runtime gem dependency on hoe & newgem

### ISSUE THREAD

**Issue by mloughran** [asplake/link_header#1]
Would you like a pull request to update the gem infrastructure to use bundler (which will remove the runtime dependencies), and to include a gemspec (so that one can bundle the git repo)?

**Comment by mjankowski** [comment]
Closing since a) this was 11 years ago, b) the change is merged.

Will handle version/changelog separately.

**Comment by asplake** [comment]
Excellent, thanks. Do I need to merge your changes or can you do that?


Mike Burrows
agendashift.com/mike <https://www.agendashift.com/mike>
Founder, Agendashift <https://www.agendashift.com/>, Co-founder, Agendashift
Academy <https://www.agendashift.com/academy>
Director, Agendashift Ltd (formerly Positive Incline Ltd)
*"Leadership and strategy in the transforming organisation"*
Email: ***@***.***
Mobile: +44 7785 236497
